### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by Tomekkkkkk** [HandsOnDataViz/leaflet-storymaps-with-google-sheets#57]
How can i add a Headmap in one part of the story?

**Comment by JackDougherty** [comment]
Can you show an example of what you mean by a headmap, such as a screenshot or link of an example from another site?

**Comment by Tomekkkkkk** [comment]
I want to Show some like this
E.g.
https://www.patrick-wied.at/static/heatmapjs/example-heatmap-leaflet.html

Maybe it's easier to Show multiple markers within a part with a hover? So if you go to part 1 New markers will Show with some Data.

I want to Show additional Data on the map for e.g income of homeowners. Maybe you have a easy solution? Thank you in advance!

**Comment by JackDougherty** [comment]
To insert your storymap inside another web page, one quick solution is to wrap the first HTML inside another HTML with an iframe. For example, see how index-frame.html displays the content of index.html in this other repo: https://github.com/JackDougherty/otl-covenants

For your other questions about showing additional data, you will need to look for other templates, or ways to modify this open-source template.
