### ISSUE TITLE
Last item in list isn't targeted

### ISSUE THREAD

**Issue by marchchad** [HandsOnDataViz/leaflet-storymaps-with-google-sheets#58]
When the browser height is greater than ~850px, the last item in the list isn't targeted and the map won't zoom to it's location.

**Comment by JackDougherty** [comment]
thanks for bug report @marchchad 

we plan to rebuild this template next month so probably won't have a fix until Dec 2016

**Comment by slead** [comment]
One workaround is to bump up the height of the `space-at-the-bottom` class;

```
#contents .space-at-the-bottom {
    height: 1000px;
    ......
}
```

**Comment by cherylhughey** [comment]
The space-at-the-bottom work around is brilliant! Thank you!
