### ISSUE TITLE
problem with move scroll fast

### ISSUE THREAD

**Issue by raficopuntiando** [HandsOnDataViz/leaflet-storymaps-with-google-sheets#59]
Hi jack

I'm trying to reproduce your story map code for my need, but I have a problem when I move the scroll fast, my geojson layers dont work well, dont remove or refresh in the new map.

The position conteiner, texts and others elementes of my story map worked with success, but the layers o geojson dont.

you may help me with may problem?

this story map is an interesting tool for me

tks

**Comment by JackDougherty** [comment]
Hi tks -- I do not have a good solution right now. My developer and i will continue to work on this issue, but it will take some time.

In the meantime, for ideas you can look at another storymap with GeoJSON layers that I created here: https://github.com/JackDougherty/otl-town-borders
