### ISSUE TITLE
Using multiple media

### ISSUE THREAD

**Issue by Kernonen** [HandsOnDataViz/leaflet-storymaps-with-google-sheets#63]
Hi ! 
thanks very much for this very useful code ! 
I'd like to know what changes could be done to allow the use of different media in chapters, like an image + a sound + whatever. 
I also would love to insert galleries instead of single image (and allow images to open full screen or in a lightbox). 
Another option could be interesting : add a column in the .csv with a link to a sag to personnalise every marker. 
Thanks very much for your help !

**Comment by ilyankou** [comment]
Hi @Kernonen:

Thank you for the suggestions.

1 - To use multiple media, we typically recommend creating another chapter with no title and no description --so that it looks as if it belongs to the chapter above it. This way we keep it simple.

2 - Embedded galleries sound fun, but I can't see how to easily implement this. Perhaps as an iframe, but then I don't think you can open the image full screen over the map, because your html document for the gallery will be bound by the iframe dimensions.

3 - Personalizing every marker is also fun - I will discuss with @JackDougherty and see if this is something we could add in the future.

Thanks!

**Comment by Kernonen** [comment]
Hi Ilya,

Thanks for your message. 

I was trying to implement FancyBox3 (https://fancyapps.com/fancybox/3/docs/#images) as a lightbox for images in container. The syntax is quite easy but I’m having a hard time to adapt it to your syntax. 
To turn an image (image.jpg) into a lightbox, the syntax is : 

<a href="image.jpg" data-fancybox data-caption="Caption for image">
	<img src=« image.jpg" alt="" />
</a>

The part of your code (story map.js) to add a media to a container is :

                                media = $('<' + mediaType + '>', {
                                        src: c['Media Link'],
                                        controls: mediaType == 'audio' ? 'controls' : '',
                                });

I guess this is where the FancyBox3 syntax should apply. I think your code will generate something like : <img>, {src : image.jpg} i.e <img src=« image.jpg » />

So the code to implement FancyBox3 to your code could be something like :

media = '<a href= "’ + c[‘Media Link’] + ‘"  data-fancybox data-caption="Caption for image « >' + 
	$('<' + mediaType + '>', { src: c['Media Link'],controls: mediaType == 'audio' ? 'controls' : ‘’,}) +
'</a>’

I made a lot of attempts but couldn’t come up with anything working. 

Any idea from your side ? 

Thank you ! 
Laurent

**Comment by Kernonen** [comment]
Hi Ilya, 

Forget about yesterday’s request. I managed to add FancyBox gallery to the Storymap project. 

Code for an image in container is now : 
 
media = $('<a href="'+ c['Media Link'] + '" data-fancybox data-caption="Caption for image">' + '<'+mediaType+' src="'+c['Media Link']+'" alt="" /></a>’);

And for a youtube video : 

media = $('<a data-fancybox href="'+ c['Media Link'] + '">' + '<img src="'+c['videoThumb']+'" alt="" /></a>’);

I added a column named videoThumb in the .csv to store video thumbnail. I guess there’s a way to automatically generate an image thumbnail from Youtube but so far didn’t find out how to do this (string parsing may be involved)

I’ll let you know if I think about more improvements. 

Laurent
