### ISSUE TITLE
suggestions for code improvements and/or tutorial tips

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-storymaps-with-google-sheets#67]
@ilyankou - Thanks to my partner Beth @jhsgh we have another interesting storymap demo (https://github.com/jhsgh/storymap) and her suggestions for code improvements and/or tutorial tips. Let's discuss whenever we have time. She writes:

All in all this is a great tool! A few things I’ve noted while working on this:
- File pathnames to media are case sensitive
- Even the .jpg extension seems to need to be lowercase. When I uploaded media with .JPG (in ALL CAPS), they would not display in the map
-Media file size can be an issue; files that are too large show up as broken links in the map. Can you add a warning about suggested max file size, or recommend that users resize images to an ideal size?

Tip:
In my storymap (https://jhsgh.github.io/storymap/) I was able to include multiple photographs of the same location by listing them in adjacent rows, leaving off the chapter name, and leaving the address info blank. 
 
Code requests:
- If feasible, I would like the option to color-code numbers on the map to categorize them. For instance in this case, synagogues established after a certain date would be a helpful category. Perhaps you could add this option as a column in the Google Sheet?
- If feasible, could there be options to change the font and size of the map title and subtitle?
- Best way to insert a logo in the title? In my map I did this by inserting a blank chapter.

Note:
- in the book tutorial, be sure to explain how to insert hyperlinks in the body of chapter text

**Comment by JackDougherty** [comment]
@ilyankou - I have moved everything from this issue to the text of chapter 13, so please close the issue if appropriate

**Comment by ilyankou** [comment]
I believe all code requests were implemented.
