### ISSUE TITLE
preparing for next release, please add CSV upload

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-storymaps-with-google-sheets#70]
Hi @ilyankou 

Here's what I've done so far to help us move ahead toward the next release

1.  Updated Google Sheet and removed old Geocoder script
2. Added your fav favicon!
3. Updated CDNs in index.html, except I'll leave leaflet-providers for you. CartoDB has updated for https, so we can pull from CDN rather than local modified code.
`<script src="https://unpkg.com/leaflet-providers@1.10.2/leaflet-providers.js"></script>`
4. Updated README

Would you please add the CSV upload feature? It is not yet working. I added a `csv` folder, where the Options Storymap Title = "My Story Map from CSV" to help you know when it is working properly. When it does, please delete the `csv` folder.

Please remove the non-master branch.

Also, when everything is ready, please make a new release version in the GitHub repo, and match it to the title of the Google Sheet

**Comment by ilyankou** [comment]
@JackDougherty 

This repo has a reverse logic: it first tries to pull data from the spreadsheet. If the spreadsheet ID is an empty string / not defined, it pulls data from a local `csv/` folder. It appears to be working for me. Do you want to change it to first try & load data from the CSV?

Btw we are missing `media/BradleyAirport.jpg` and `media/mclean.mp3` from your most recent merge.

**Comment by JackDougherty** [comment]
Good to know. Would you please make the logic the same for the two Leaflet with Google Sheets repos?

Here's my understanding of the two current logics:

#1 - first looks for Options.csv in CSV folder, then looks for sheet ID in google-doc-url.js
#2 - first looks for sheet ID in google-doc-url.js, then looks for Options.csv in CSV folder

I have a slight preference for #1 because it will be easier for us to troubleshoot problems in the future. But if you prefer #2, that's fine, too.

PS: I replaced the missing media from my messed-up pull request. Sorry about that!

**Comment by ilyankou** [comment]
Fixed with the No 1 suggestion.
