### ISSUE TITLE
Help proposed

### ISSUE THREAD

**Issue by Kernonen** [HandsOnDataViz/leaflet-storymaps-with-google-sheets#76]
Hello, 
I've been building interactive maps from your code and have brought many addons (icon customization, geojson overlay with interactive actions, element properties display in narrative, lightbox for fullscreen image and video display). I would like to propose you my help if ever you are to wish to add this elements in the native code. This additions may not be perfect but they may help you take them further. 
Here are some exemples :
https://www.weneedtotalkabouttheborder.eu 
https://www.laurentgontier.com/Storymap_Normandie/
In the latest, check for "CITÉ DE SOYE" chapter on the page (use search function for the browser) to see a geojson overlay exemple (polygons are clickable); Red polygons have popup with photos.
Thank you very much for your good work ! 
Laurent

**Comment by JackDougherty** [comment]
Thanks @Kernonen for sharing your excellent storymap examples and offering to share your code. 
I have added links to your examples to this section of our book-in-progress, which we are working to finish soon.
https://handsondataviz.org/leaflet-storymaps-with-google-sheets.html
When map developer @ilyankou  or I have time to review your work, one of us will follow up with you.

**Comment by Kernonen** [comment]
Pleasure will be mine. 
Feel free to contact me. 
Also, I was also planing on adding an opacity slider to chapters in order to allow progressive transparency to map overlays. 
Keep up te good work
Laurent

**Comment by ilyankou** [comment]
Hi Laurent–

We've added your Border storymap to our small gallery of examples in the [HandsOnDataViz book](https://handsondataviz.org/leaflet-storymaps-with-google-sheets.html), which will also appear in print in April 2021 (eg [see on Amazon](https://www.amazon.com/gp/product/1492086002)). We will leave the template as it is for now, but 1–we will keep your suggestions in mind for when we decide to tweak it, and 2–your examples are a great illustration that the storymaps can be improved with a bit of coding.

Thanks!
Ilya

**Comment by Kernonen** [comment]
Hi Ilya, 
Thank you very much for your mail. 
I would be happy to get the book when it’s out. Where would I be able to purchase it ? 
Best and happy new year
Laurent Gontier

**Comment by ilyankou** [comment]
@Kernonen Happy New Year to you too, Laurent! I suggest [bookmarking this Amazon page](https://www.amazon.com/gp/product/1492086002) for now, but once we get more information on distributors, we'll make sure to update [HandsOnDataViz.org](https://handsondataviz.org/). Thank you!
