### ISSUE TITLE
Change base map drop down on google sheet

### ISSUE THREAD

**Issue by MarkJThomas** [HandsOnDataViz/leaflet-storymaps-with-google-sheets#79]
Hiya, 

I would like to add: Esri.WorldImagery and a few others  to the dropdown on the 'Options' tab under Base Maps on the google sheets template, can you advise how I can do that please?

The main reason for wanting to do this is because the other base maps don't cover the area where I want my story map so it just shows as grey.

All the best,
Mark

**Comment by ilyankou** [comment]
Hi Mark–

We are using [leaflet-providers](http://leaflet-extras.github.io/leaflet-providers/preview/) plugin to load basemaps, so you should be able to manually edit the cell to load a different basemap (in your case, `Esri.WorldImagery`).

Let me know if that helps!

Ilya
