### ISSUE TITLE
A missing >  ?

### ISSUE THREAD

**Issue by patrickmj** [HandsOnDataViz/leaflet-storymaps-with-google-sheets#81]
Not sure if I'm missing something in how the pages are getting put together. Sorry if I am, but it seems like this should have a closing `>` 

``` mediaContainer = $('<div></div', { ```

https://github.com/HandsOnDataViz/leaflet-storymaps-with-google-sheets/blob/a25746cdbf2e52390df20f77c34811840348b4f7/scripts/storymap.js#L206

Probably something that browsers just deal with, but noticed it as I was browsing the code and was curious if I'm missing something.

Thanks! I'm loving this solution to lots of problems!

**Comment by JackDougherty** [comment]
@ilyankou - do you have time to address this question from @patrickmj ?  Thanks!

**Comment by ilyankou** [comment]
Great catch, thanks @patrickmj! Should be fixed now.
